#!/usr/bin/env bash
# Count the alerts generated by the dataset, grouped by rule. Quick sanity
# check of what the currently loaded ruleset classified.
set -euo pipefail
cd "$(dirname "$0")/.."
CT=$(cd stack && docker compose ps -q wazuh.manager)
[ -n "$CT" ] || { echo "manager is not running — run 'make up'"; exit 1; }

echo "=== alerts by rule (rule.id | level | count | description) ==="
docker exec "$CT" sh -c 'cat /var/ossec/logs/alerts/alerts.json 2>/dev/null' \
  | python3 -c '
import sys, json, collections
c = collections.Counter(); meta = {}
for line in sys.stdin:
    line = line.strip()
    if not line: continue
    try: a = json.loads(line)
    except json.JSONDecodeError: continue
    r = a.get("rule", {})
    rid = r.get("id")
    if not rid: continue
    c[rid] += 1; meta[rid] = (r.get("level"), r.get("description", "")[:60])
for rid, n in c.most_common(40):
    lvl, desc = meta[rid]
    print(f"  {rid:>7} | lvl {lvl:>2} | {n:>4}x | {desc}")
print(f"\n  total alerts: {sum(c.values())}")
'
