#!/usr/bin/env bash
# Write a ready-to-use .env for the optional full replay.
#
# The Wazuh stack needs three passwords and the bcrypt hashes of two of them.
# Doing that by hand means installing apache2-utils for htpasswd and pasting
# hashes into a file, which is a manual step that can go wrong. The full replay
# already requires Docker, so the hashes are computed in a throwaway container
# and nothing new is installed on the host.
#
#   ./scripts/make-env.sh          # write .env (refuses to overwrite)
#   ./scripts/make-env.sh --force  # overwrite an existing .env
#
# .env is gitignored and never leaves this machine.
set -euo pipefail
cd "$(dirname "$0")/.."

FORCE="${1:-}"
if [ -f .env ] && [ "$FORCE" != "--force" ]; then
  echo ".env already exists; not touching it. Re-run with --force to replace it." >&2
  exit 1
fi

command -v docker >/dev/null || { echo "need: docker (the full replay needs it anyway)" >&2; exit 1; }

# Wazuh rejects a password that has no special character ("Error 5007 -
# Insecure user password provided") and the manager then crash-loops, so build
# each password with one lowercase, one uppercase, one digit and one special
# from the set Wazuh accepts, then pad and shuffle.
#
# Read a bounded chunk FIRST, then filter: piping an unbounded /dev/urandom into
# `head -c` closes the pipe early, and under `set -o pipefail` the SIGPIPE on the
# producer aborts the whole script.
rand_from () { head -c 2048 /dev/urandom | LC_ALL=C tr -dc "$1" | cut -c1-"$2"; }
pw () {
  local body special all
  body=$(rand_from 'A-Za-z0-9' 20)
  special=$(rand_from '.*+?_-' 1)
  # guarantee one of each class regardless of what the random draw produced
  all="${body}${special}aZ7"
  printf '%s' "$all" | fold -w1 | shuf | tr -d '\n'
}

bcrypt () { docker run --rm httpd:2.4-alpine htpasswd -bnBC 12 "" "$1" | sed -n 's/^://p'; }

ADMIN_PASSWORD="$(pw)"
KIBANASERVER_PASSWORD="$(pw)"
API_PASSWORD="$(pw)"

echo "computing bcrypt hashes in a throwaway container..."
ADMIN_HASH="$(bcrypt "$ADMIN_PASSWORD")"
KIBANASERVER_HASH="$(bcrypt "$KIBANASERVER_PASSWORD")"

cat > .env <<EOF
# Generated by scripts/make-env.sh. Local lab only, never committed.
WAZUH_VERSION=4.14.5

ADMIN_PASSWORD=$ADMIN_PASSWORD
KIBANASERVER_PASSWORD=$KIBANASERVER_PASSWORD
API_PASSWORD=$API_PASSWORD

ADMIN_HASH='$ADMIN_HASH'
KIBANASERVER_HASH='$KIBANASERVER_HASH'

DASHBOARD_PORT=8444
COMPOSE_PROJECT_NAME=wazuhstudy

# Any local path you own; the stack keeps its state here. Deliberately OUTSIDE
# the working tree: the containers write it as root, so keeping it in the repo
# would fill 'git status' with files you cannot even read.
DATA_DIR=${DATA_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/wazuh-study}
EOF

# Create it now, as the invoking user. If the first thing to touch this path is
# a docker bind mount, Docker creates it as root and run.sh then needs sudo.
mkdir -p "${DATA_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/wazuh-study}"

echo "wrote .env with freshly generated credentials"
echo "  dashboard port : 8444"
echo "  state directory: ${DATA_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/wazuh-study}"
echo "next: ./run.sh --fresh"
