#!/usr/bin/env bash
# Write a ready-to-use .env for the optional full replay.
#
# The Wazuh stack needs three passwords and the bcrypt hashes of two of them.
# Doing that by hand means installing apache2-utils for htpasswd and pasting
# hashes into a file, which is a manual step that can go wrong. The full replay
# already requires Docker, so the hashes are computed in a throwaway container
# and nothing new is installed on the host.
#
#   ./scripts/make-env.sh          # write .env (refuses to overwrite)
#   ./scripts/make-env.sh --force  # overwrite an existing .env
#
# .env is gitignored and never leaves this machine.
set -euo pipefail
cd "$(dirname "$0")/.."

FORCE="${1:-}"
if [ -f .env ] && [ "$FORCE" != "--force" ]; then
  echo ".env already exists; not touching it. Re-run with --force to replace it." >&2
  exit 1
fi

command -v docker >/dev/null || { echo "need: docker (the full replay needs it anyway)" >&2; exit 1; }

# Read a bounded chunk FIRST, then filter. Piping an unbounded /dev/urandom
# into `head -c` closes the pipe early, and under `set -o pipefail` the SIGPIPE
# on the producer aborts the whole script.
pw () { head -c 512 /dev/urandom | LC_ALL=C tr -dc 'A-Za-z0-9' | cut -c1-24; }
# htpasswd prints ":<hash>" followed by a blank line, so pick the line that
# actually carries the hash instead of taking the last one.
bcrypt () { docker run --rm httpd:2.4-alpine htpasswd -bnBC 12 "" "$1" | sed -n 's/^://p'; }

ADMIN_PASSWORD="$(pw)"
KIBANASERVER_PASSWORD="$(pw)"
API_PASSWORD="$(pw)"

echo "computing bcrypt hashes in a throwaway container..."
ADMIN_HASH="$(bcrypt "$ADMIN_PASSWORD")"
KIBANASERVER_HASH="$(bcrypt "$KIBANASERVER_PASSWORD")"

cat > .env <<EOF
# Generated by scripts/make-env.sh. Local lab only, never committed.
WAZUH_VERSION=4.14.5

ADMIN_PASSWORD=$ADMIN_PASSWORD
KIBANASERVER_PASSWORD=$KIBANASERVER_PASSWORD
API_PASSWORD=$API_PASSWORD

ADMIN_HASH='$ADMIN_HASH'
KIBANASERVER_HASH='$KIBANASERVER_HASH'

DASHBOARD_PORT=8444
COMPOSE_PROJECT_NAME=wazuhstudy

# Any local path you own; the stack keeps its state here.
DATA_DIR=${DATA_DIR:-$PWD/.wazuh-data}
EOF

echo "wrote .env with freshly generated credentials"
echo "  dashboard port : 8444"
echo "  state directory: ${DATA_DIR:-$PWD/.wazuh-data}"
echo "next: ./run.sh --fresh"
